steps:
  - name: 'gcr.io/${PROJECT_ID}/buildtool.npm'
    volumes:
      - name: root
        path: /root
    args:
      - 'ci'
  - name: 'gcr.io/${PROJECT_ID}/buildtool.npm'
    volumes:
      - name: root
        path: /root
    args:
      - 'run'
      - 'build'
  - name: 'gcr.io/${PROJECT_ID}/buildtool.npm'
    volumes:
      - name: root
        path: /root
    args:
      - 'audit'
